CREATE TABLE AuditLogs (
    LogID SERIAL PRIMARY KEY,
    AdminID INT REFERENCES Admin(AdminID) ON DELETE CASCADE,
    Action VARCHAR(255) NOT NULL,
    Timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
