CREATE TABLE OTPs (
    OTPID SERIAL PRIMARY KEY,
    UserID INT REFERENCES Users(UserID) ON DELETE CASCADE,
    OTPCode VARCHAR(6) NOT NULL,
    ExpiryTime TIMESTAMP NOT NULL,
    IsUsed BOOLEAN DEFAULT FALSE,
    ResendCount INT DEFAULT 0,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
